In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [55]:
dataset = pd.read_csv(r'C:\Users\josemaria\Desktop\ML_Udemy\Datasets\Preprocessing\Data.csv')


In [56]:
# Hay que escribir una "r" delante de la ruta de carga del fichero porque si no no te lee el documento. 

In [57]:
# Vista del fichero que acabamos de ver

In [58]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [59]:
# iloc hace referencia al lugar que ocupan los datos en la matriz. Los primeros dos puntos dentro del corchete significan "todas las filas"

In [60]:
# Los siguientes dos puntos -1 significan "todas las columnas excepto la última"

In [61]:
X = dataset.iloc[:,:-1]

In [62]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [63]:
#Ahora vamos a cargar la variable dependiente (y) en otra variable: "todas las filas de la columna 3" (posición inicial = 0). Por tanto, col 4 = posición 3.

In [64]:
y = dataset.iloc[:,3]

In [65]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [66]:
from sklearn.impute import SimpleImputer 

In [67]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [68]:
imputer=imputer.fit(X.iloc[:,1:3])

In [69]:
# Nos separamos ligeramente del código del profesor ya que no usa la cláusula .iloc cuando llama a X. 

In [70]:
X.iloc[:,1:3] = imputer.transform(X.iloc[:,1:3])

In [71]:
X

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [72]:
# La traducción no es del todo correcta ya que los números usados para representar los países se pueden comparar entre sí. 

In [73]:
# La mejor forma es crear una variable dummy por cada país con un 1 o un 0 en función de si pertenece a ese país. 

In [87]:
X = pd.get_dummies(data = X)

In [88]:
X

Age        Salary  Country_France  Country_Germany  Country_Spain
0  44.000000  72000.000000               1                0              0
1  27.000000  48000.000000               0                0              1
2  30.000000  54000.000000               0                1              0
3  38.000000  61000.000000               0                0              1
4  40.000000  63777.777778               0                1              0
5  35.000000  58000.000000               1                0              0
6  38.777778  52000.000000               0                0              1
7  48.000000  79000.000000               1                0              0
8  50.000000  83000.000000               0                1              0
9  37.000000  67000.000000               1                0              0

In [84]:
# Pasamos a binario la variable y también. 

In [89]:
from sklearn.preprocessing import LabelEncoder

In [90]:
labelencoder_y = LabelEncoder()

In [91]:
y = labelencoder_y.fit_transform(y)

In [92]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
# Ahora dividiremos el dataset en conjunto entrenamiento y conjunto de testing. 

In [94]:
from sklearn.model_selection import train_test_split

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [96]:
X_train

Age        Salary  Country_France  Country_Germany  Country_Spain
4  40.000000  63777.777778               0                1              0
9  37.000000  67000.000000               1                0              0
1  27.000000  48000.000000               0                0              1
6  38.777778  52000.000000               0                0              1
7  48.000000  79000.000000               1                0              0
3  38.000000  61000.000000               0                0              1
0  44.000000  72000.000000               1                0              0
5  35.000000  58000.000000               1                0              0

In [97]:
X_test

Age   Salary  Country_France  Country_Germany  Country_Spain
2  30.0  54000.0               0                1              0
8  50.0  83000.0               0                1              0

In [98]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [99]:
y_test

array([0, 0])

In [ ]:
# Escalado (normalización, estandarización) de variables. Usaremos standard_scaler

In [101]:
from sklearn.preprocessing import StandardScaler

In [103]:
sc_X = StandardScaler ()

In [105]:
X_train = sc_X.fit_transform(X_train)

In [108]:
X_test = sc_X.transform(X_test)

In [109]:
X_train

array([[ 0.26306757,  0.12381479, -1.        ,  2.64575131, -0.77459667],
       [-0.25350148,  0.46175632,  1.        , -0.37796447, -0.77459667],
       [-1.97539832, -1.53093341, -1.        , -0.37796447,  1.29099445],
       [ 0.05261351, -1.11141978, -1.        , -0.37796447,  1.29099445],
       [ 1.64058505,  1.7202972 ,  1.        , -0.37796447, -0.77459667],
       [-0.0813118 , -0.16751412, -1.        , -0.37796447,  1.29099445],
       [ 0.95182631,  0.98614835,  1.        , -0.37796447, -0.77459667],
       [-0.59788085, -0.48214934,  1.        , -0.37796447, -0.77459667]])